name: Spearforge Weekly Newsletter
on:
  schedule:
    - cron: '30 1 * * 5' # 7:00 AM IST is 1:30 AM UTC
  workflow_dispatch: # Allows you to run it manually to test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -U google-generativeai
      - name: Run Newsletter Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python main.py
